===<DATA>==========================================
 1- Patologias e procedimentos associados:
    ( ) HAS             ( ) DEMENCIA             ( ) AVC
    ( ) DM              ( ) ESCARAS              ( ) AMPUTAÇÃO
    ( ) TRAQUEOSTOMIA   ( ) SONDA URINÁRIA       ( ) SONDA NASO-ENTERAL
    ( ) NEOPLASIA
    CARDIOPATIAS:       ( ) ARRITMIA             ( ) CORONARIOPATIA
    ( ) MIOCARDIOPATIA  ( ) CHAGAS               ( ) OUTROS

 2- Principal motivo de solicitação da Medicar:

 3- Medicações e posologia diárias:

 4- Locais de atendimentos e profissionais da saúde envolvidos:

 5- O associado tem cuidadores?
 ( ) Não
 ( ) Sim

 6- Necessita suporte de enfermagem?
 ( ) Sim                ( ) Não
 7- Necessita suporte nutricional?
 ( ) Sim                ( ) Não
 8- Necessita fisioterapia?
 ( ) Sim                ( ) Não
 9- Necessita fonoaudiologia?
 ( ) Sim                ( ) Não

 10- Condições adequadas de moradia?
 ( ) Sim                ( ) Não

 11- Condições adequadas de higiene e saneamento?
 ( ) Sim                ( ) Não

