CREATE TABLE 'FILIAL.DBF' ;
               NAME 'FILIAL' ;
                     (IDFILIAL C(2) NOT NULL, ;
                     NOME C(40) NOT NULL, ;
                     CGC C(18) NOT NULL, ;
                     INSCR_ESTADUAL C(15) NOT NULL, ;
                     TELEFONE C(14) NOT NULL, ;
                     FAX C(14) NOT NULL, ;
                     FONE_CENTRAL C(14) NOT NULL, ;
                     ENDERECO C(40) NOT NULL, ;
                     COMPLEMENTO C(20) NOT NULL, ;
                     BAIRRO C(20) NOT NULL, ;
                     CIDADE C(25) NOT NULL, ;
                     ESTADO C(2) NOT NULL, ;
                     CEP C(10) NOT NULL, ;
                     PAPEL C(80) NOT NULL, ;
                     LOGOTIPO G NOT NULL, ;
                     COR I NOT NULL, ;
                     ATD_TR_EMERGENCIA I NOT NULL, ;
                     ATD_TR_URGENCIA I NOT NULL, ;
                     ATD_TR_CONSULTA I NOT NULL, ;
                     ATD_IMPRIMIR_CHAMADOS L NOT NULL, ;
                     ATD_AUTOATUALIZA L NOT NULL, ;
                     ATD_TEMPOATUALIZA I NOT NULL, ;
                     NF_IR N(6, 2) NOT NULL, ;
                     NF_IR_LIMITE Y NOT NULL, ;
                     NF_INSS N(6, 2) NOT NULL, ;
                     NF_INSS_LIMITE Y NOT NULL, ;
                     NF_ISS N(6, 2) NOT NULL, ;
                     NF_COFINS N(6, 2) NOT NULL, ;
                     NF_CSOCIAL N(6, 2) NOT NULL, ;
                     NF_PIS N(6, 2) NOT NULL, ;
                     CTA_FATURAMENTO C(100) NOT NULL, ;
                     CONTRATO_EVENTO I NOT NULL, ;
                     CONTRATO_PARTICULAR I NOT NULL, ;
                     ATEND L NOT NULL DEFAULT .T.,;
                     CNAE  C(10) NOT NULL,;
                     SIAFI C(10) NOT NULL,;
                     IM    C(18) NOT NULL ;               
                     )
