SET ANSI OFF
SET ASSERTS OFF
SET AUTOSAVE OFF
SET BELL OFF
SET BROWSEIMECONTROL OFF
SET BRSTATUS OFF
SET CARRY OFF
SET CENTURY OFF
SET CLEAR OFF
SET CLOCK OFF
SET COMPATIBLE OFF
SET CONFIRM ON
SET CONSOLE ON
SET CPDIALOG OFF
SET CURSOR ON
SET DEBUG OFF
SET DECIMALS TO 7
SET DELETED ON
SET DELIMITERS OFF
SET DEVELOPMENT OFF
SET DEVICE TO SCREEN
SET DOHISTORY OFF
SET ECHO OFF
SET ESCAPE OFF
SET EVENTTRACKING OFF
SET EXACT OFF
SET EXCLUSIVE OFF
SET FIELDS OFF
SET FIXED OFF
SET FULLPATH ON
SET HEADINGS OFF
SET HELP OFF
SET HOURS TO 24
SET INTENSITY OFF
SET LOCK OFF
SET LOGERRORS OFF
SET MARGIN TO 0
SET MOUSE ON
SET MULTILOCKS ON
SET NEAR  OFF
SET NOTIFY OFF
SET OLEOBJECT ON
SET OPTIMIZE ON
SET PALETTE ON
SET PRINTER OFF
SET READBORDER OFF
SET REPROCESS TO 3 SECONDS
SET RESOURCE OFF
SET SAFETY OFF
SET SECONDS ON
SET SPACE ON
SET STATUS OFF
SET STATUS BAR OFF
SET STEP OFF
SET SYSFORMATS ON
SET TALK OFF
SET TEXTMERGE OFF
SET TRBETWEEN OFF
SET UDFPARMS VALUE
SET UNIQUE OFF
